name: timesheet
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  auto_route: ^5.0.4
  bloc: ^8.1.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_datetime_picker: ^1.5.1
  flutter_svg: ^1.1.6
  formz: ^0.4.1
  get_it: ^7.2.0
  intl: ^0.18.0
  json_annotation: ^4.7.0

dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.5.4
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter_regular.ttf
        - asset: assets/fonts/inter_bold.ttf
        - asset: assets/fonts/inter_thin.ttf
        - asset: assets/fonts/inter_semi_bold.ttf
        - asset: assets/fonts/inter_medium.ttf
